#164798204  create user profile
andela/ah-backend-sparta pull request #11
Opened 2019-04-01 12:22 UTC by felixkiryowa

#### What does this PR do?
Users should be able to create their profiles
#### Description of Task to be completed?
User should be able to create profiles on successful login
#### How should this be manually tested?

[#164798204](https://www.pivotaltracker.com/story/show/164798204)

2019-04-01 13:15 UTC, ja-odur commented on requirements.txt
> +asn1crypto==0.24.0
@felixkiryowa please use `pipenv run pipenv_to_requirements` to generate the `requirements.txt` file

2019-04-01 13:16 UTC, ja-odur commented on Pipfile
> +django-rest-swagger = "*"
@felixkiryowa how come you have this requirement

2019-04-03 06:24 UTC, ja-odur commented on authors/apps/profiles/views.py
> +        profile = Profile.objects.get(username=kwargs["username"])
@felixkiryowa why do you have repeated definition of profile i.e. on line `43 and 44`

2019-04-03 10:49 UTC, dorothyas submitted a review, later dismissed

2019-04-03 11:18 UTC, dorothyas submitted a review, later dismissed

2019-04-03 12:14 UTC, dannylwe submitted a review, later dismissed

2019-04-03 12:33 UTC, ezrogha requested changes
Great work, kindly make those few changes

2019-04-03 12:33 UTC, ezrogha commented on authors/apps/profiles/models.py
> +from django.conf import settings
Hey @felixkiryowa & @dorothyas this import is unused,  please remove it

2019-04-03 12:33 UTC, ezrogha commented on authors/apps/profiles/tests/test_data.py
> +}
please a new line at the end of this file

2019-04-03 12:33 UTC, ezrogha commented on authors/apps/profiles/urls.py
> +]
Also add a new line to the end of this file

2019-04-03 12:45 UTC, ezrogha approved these changes

2019-04-03 12:53 UTC, dorothyas approved these changes

2019-04-03 12:59 UTC, ja-odur approved these changes
LGTM

2019-04-03 13:00 UTC, merged