#164798214 Pagination support for articles
andela/ah-backend-sparta pull request #17
Opened 2019-04-08 16:14 UTC by ezrogha

#### What does this PR do?
Adds pagination to articles

#### Description of Task to be completed?
Pagination seperates all articles into discrete pages

#### How should this be manually tested?
- Fetch branch `git fetch origin ft-setup-social-auth-164798203`
- Checkout `git checkout ft-setup-social-auth-164798203`
- Run `pipenv install` to install packages
- Run `python manage.py runserver`
- Visit http://127.0.0.1:8000/api/articles/

#### What are the relevant pivotal tracker stories?
[#164798214](https://www.pivotaltracker.com/story/show/164798214)

#### Screenshots (if appropriate)
<img width="347" alt="Screenshot 2019-04-08 at 19 08 13" src="https://user-images.githubusercontent.com/35653907/55739493-d67e2780-5a31-11e9-9e6f-e14764f06c8a.png">

2019-04-08 18:24 UTC, dannylwe submitted a review, later dismissed
Good work, no complaints here.

2019-04-09 08:36 UTC, ja-odur requested changes
@ezrogha Please set the default limit to 10 and rename the `offset` to `page`.
add documentaion as well.

2019-04-09 13:50 UTC, ja-odur approved these changes
LGTM

2019-04-09 13:50 UTC, felixkiryowa approved these changes

2019-04-09 13:52 UTC, dannylwe approved these changes

2019-04-09 13:52 UTC, dorothyas approved these changes

2019-04-09 13:53 UTC, merged